using DKP.Application.Authentication; using DKP.Application.Persistence; using DKP.Domain; using DKP.Facade.Commands; using DKP.Facade.Contracts;
namespace DKP.Application.Presets;
public sealed class DkpPresetCommandService(IUserRepository users, IPresetRepository presets, IDkpTransactionRepository transactions, TimeProvider time) : IDkpPresetCommands
{
	private async Task<User> Actor(string id,CancellationToken ct)=>await users.FindByDiscordIdAsync(id,ct)??throw new UnauthorizedAccessException("Authenticated user does not exist.");
	private static void Officer(User u){if(u.Role!=UserRole.Officer)throw new UnauthorizedAccessException("Only Officers can manage presets.");}
	private static void Valid(DkpAwardPresetInput x){if(string.IsNullOrWhiteSpace(x.Name)||string.IsNullOrWhiteSpace(x.Reason)||x.Reason.Trim().Length>500||x.Amount<=0||x.MaxApplicationsPerUser<=0)throw new ArgumentException("Invalid preset.");}
	public async Task<DkpAwardPresetDto> CreateAsync(string id,DkpAwardPresetInput x,CancellationToken ct=default){var a=await Actor(id,ct);Officer(a);Valid(x);var p=new DkpAwardPreset(x.Name.Trim(),x.Amount,x.Reason.Trim(),x.MaxApplicationsPerUser,time.GetUtcNow().UtcDateTime);await presets.AddAsync(p,ct);await presets.SaveChangesAsync(ct);return new(p.Id,p.Name,p.Amount,p.Reason,p.MaxApplicationsPerUser,p.IsActive);}
	public async Task<DkpAwardPresetDto> UpdateAsync(string id,Guid pid,DkpAwardPresetInput x,CancellationToken ct=default){var a=await Actor(id,ct);Officer(a);Valid(x);var p=await presets.FindAsync(pid,ct)??throw new KeyNotFoundException("Preset not found.");p.Update(x.Name.Trim(),x.Amount,x.Reason.Trim(),x.MaxApplicationsPerUser,time.GetUtcNow().UtcDateTime);await presets.SaveChangesAsync(ct);return new(p.Id,p.Name,p.Amount,p.Reason,p.MaxApplicationsPerUser,p.IsActive);}
	public async Task SetActiveAsync(string id,Guid pid,bool active,CancellationToken ct=default){var a=await Actor(id,ct);Officer(a);var p=await presets.FindAsync(pid,ct)??throw new KeyNotFoundException("Preset not found.");p.SetActive(active,time.GetUtcNow().UtcDateTime);await presets.SaveChangesAsync(ct);}
	public async Task<DkpTransactionDto> ApplyAsync(string id,Guid targetId,Guid pid,CancellationToken ct=default){var a=await Actor(id,ct);Officer(a);var target=await users.FindByIdAsync(targetId,ct)??throw new KeyNotFoundException("Target not found.");if(target.IsBlocked)throw new InvalidOperationException("Target is blocked.");var p=await presets.FindAsync(pid,ct)??throw new KeyNotFoundException("Preset not found.");if(!p.IsActive)throw new InvalidOperationException("Preset is inactive.");if(await presets.GetUsageCountAsync(target.Id,p.Id,ct)>=p.MaxApplicationsPerUser)throw new InvalidOperationException("Preset lifetime limit reached.");var now=time.GetUtcNow().UtcDateTime;var tx=new DkpTransaction(target.Id,p.Amount,p.Reason,a.Id,now);var use=new DkpAwardPresetApplication(p.Id,target.Id,tx.Id,a.Id,now);await transactions.AddAsync(tx,ct);await presets.AddApplicationAsync(use,ct);await presets.SaveChangesAsync(ct);return new(tx.Id,tx.Amount,tx.Reason,tx.CreatedAtUtc,a.DiscordName);}
}
