<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DKP.Domain\DKP.Domain.csproj" />
    <ProjectReference Include="..\DKP.Facade\DKP.Facade.csproj" />
  </ItemGroup>

</Project>
