<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DKP.Application\DKP.Application.csproj" />
    <ProjectReference Include="..\DKP.Domain\DKP.Domain.csproj" />
    <ProjectReference Include="..\DKP.Infrastructure\DKP.Infrastructure.csproj" />
    <ProjectReference Include="..\DKP.Blazor\DKP.Blazor.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

</Project>
