<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>DKP.Blazor-Development</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DKP.Api\DKP.Api.csproj" />
    <ProjectReference Include="..\DKP.Facade\DKP.Facade.csproj" />
    <ProjectReference Include="..\DKP.InversionOfControl\DKP.InversionOfControl.csproj" />
    <PackageReference Include="Radzen.Blazor" />
  </ItemGroup>

</Project>
